#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top48
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top48 {base} {
    if {$base == ""} {
        set base .top48
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 295x193+505+325
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1268 989
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "About - Windows 10 Service Tool"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::label $top.tLa49 \
        -background {#d9d9d9} -foreground {#000000} \
        -font {-size 14 -weight bold} -relief flat -text {win10srv 1.0} 
    vTcl:DefineAlias "$top.tLa49" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa50 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {A small tool to reset the Windows 10} 
    vTcl:DefineAlias "$top.tLa50" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa51 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Copyright (C) 2017 Ikem Krueger} 
    vTcl:DefineAlias "$top.tLa51" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa52 \
        -background {#d9d9d9} -foreground blue -font {-size 9 -underline 1} \
        -relief flat -text https://github.com/ikem-krueger/win10srv \
        -cursor hand2 
    vTcl:DefineAlias "$top.tLa52" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu54 \
        -takefocus {} -text Close -underline 0 
    vTcl:DefineAlias "$top.tBu54" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa37 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {services back to their default states.} 
    vTcl:DefineAlias "$top.tLa37" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa49 \
        -in $top -x 90 -y 20 -anchor nw -bordermode ignore 
    place $top.tLa50 \
        -in $top -x 50 -y 50 -anchor nw -bordermode ignore 
    place $top.tLa51 \
        -in $top -x 60 -y 100 -anchor nw -bordermode ignore 
    place $top.tLa52 \
        -in $top -x 30 -y 130 -anchor nw -bordermode ignore 
    place $top.tBu54 \
        -in $top -x 210 -y 160 -anchor nw -bordermode ignore 
    place $top.tLa37 \
        -in $top -x 50 -y 70 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top48

