#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top38
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top38 {base} {
    if {$base == ""} {
        set base .top38
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 270x166+428+169
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1276 997
    wm minsize $top 130 10
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::label $top.tLa39 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text Service: 
    vTcl:DefineAlias "$top.tLa39" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa40 \
        -background {#d9d9d9} -foreground {#000000} -relief flat -text None 
    vTcl:DefineAlias "$top.tLa40" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa41 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text Status: 
    vTcl:DefineAlias "$top.tLa41" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa42 \
        -background {#d9d9d9} -foreground {#000000} -relief flat -text None 
    vTcl:DefineAlias "$top.tLa42" "TLabel4" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa43 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text Success: 
    vTcl:DefineAlias "$top.tLa43" "TLabel5" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa44 \
        -background {#d9d9d9} -foreground {#000000} -relief flat -text 0 
    vTcl:DefineAlias "$top.tLa44" "TLabel6" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa45 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text Failure: 
    vTcl:DefineAlias "$top.tLa45" "TLabel7" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa46 \
        -background {#d9d9d9} -foreground {#000000} -relief flat -text 0 
    vTcl:DefineAlias "$top.tLa46" "TLabel8" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar $top.tPr47
    vTcl:DefineAlias "$top.tPr47" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu48 \
        -takefocus {} -text About -underline 0 
    vTcl:DefineAlias "$top.tBu48" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu49 \
        -takefocus {} -text Log -underline 0 
    vTcl:DefineAlias "$top.tBu49" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu50 \
        -takefocus 1 -text Repair -underline 0 -state disabled 
    vTcl:DefineAlias "$top.tBu50" "TButton3" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa39 \
        -in $top -x 10 -y 10 -anchor nw -bordermode ignore 
    place $top.tLa40 \
        -in $top -x 60 -y 10 -anchor nw -bordermode ignore 
    place $top.tLa41 \
        -in $top -x 10 -y 30 -anchor nw -bordermode ignore 
    place $top.tLa42 \
        -in $top -x 60 -y 30 -anchor nw -bordermode ignore 
    place $top.tLa43 \
        -in $top -x 10 -y 50 -anchor nw -bordermode ignore 
    place $top.tLa44 \
        -in $top -x 60 -y 50 -anchor nw -bordermode ignore 
    place $top.tLa45 \
        -in $top -x 10 -y 70 -anchor nw -bordermode ignore 
    place $top.tLa46 \
        -in $top -x 60 -y 70 -anchor nw -bordermode ignore 
    place $top.tPr47 \
        -in $top -x 10 -y 100 -width 250 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu48 \
        -in $top -x 10 -y 130 -anchor nw -bordermode ignore 
    place $top.tBu49 \
        -in $top -x 100 -y 130 -anchor nw -bordermode ignore 
    place $top.tBu50 \
        -in $top -x 180 -y 130 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top38

